### ISSUE TITLE
PDF could not be created

### ISSUE THREAD

**Issue by atefBB** [wemersonjanuario/pdf#3]
Hey.
I got this error : 
`PDF could not be created`.
any ideas to solve it?
I'm using this code :
`$pdf = new Inline\PDF\PDF('/usr/bin/wkhtmltopdf');
    echo $pdf->loadHTML('<b>Hello World</b>')->get();`

**Comment by wemersonjanuario** [comment]
Sorry for delay. Still having problem?

**Comment by atefBB** [comment]
NO!

**Comment by wemersonjanuario** [comment]
Very nice
